TEXTS = {
    'uz': {
        'welcome': 'Assalomu alaykum!',
        'choose_lang': 'Tilni tanlang:',
        'offer': 'Iltimos ofertani o‘qib chiqing: <a href="https://example.com/oferta">Oferta</a>\nAgar rozilik bersangiz — "Tasdiqlayman ✅" tugmasini bosing.',
        'offer_confirmed': '💡 Endi siz SunLite botidan foydalanishingiz mumkin!\nQuyidagi menyudan tanlang 👇',
        'enter_topup_amount': '💳 Hisobni to‘ldirish\n\n💬 Kiriting: qancha summa to‘ldirmoqchisiz?\n(Minimal: {min} UZS, Maksimal: {max} UZS)',
        'invalid_amount': 'Noto‘g‘ri summa. Iltimos butun son kiriting va {min}-{max} oralig‘ida bo‘lsin.',
        'send_screenshot': '📸 To‘lovni amalga oshirganingizdan so‘ng skrinshot yuboring!',
        'topup_sent_admin': 'Sizning to‘lovingiz adminga yuborildi. Tasdiqlanishini kuting.',
        'topup_approved': '🎉 Hisobingiz muvaffaqiyatli {amount} UZS ga to‘ldirildi!',
        'topup_rejected': 'To‘lov rad etildi. Iltimos admin bilan bog‘laning.',
        'no_history': '📜 Tarixda hozircha hech narsa yo‘q.',
        'ask_nickname': 'Iltimos server uchun nickname kiriting (bu qaytarilmaydi):',
        'order_sent_admin': '🆕 Buyurtma adminga yuborildi. Tasdiqlanishini kuting.',
        'order_confirmed_user': '✅ Buyurtmangiz muvaffaqiyatli serverdan hisobingizga yuborildi.',
        'insufficient_balance': 'Balans yetarli emas. Iltimos hisobni to‘ldiring.',
        'cancelled': 'Amaliyot bekor qilindi 🔙',
        'admin_broadcast_prompt': 'Iltimos yuboriladigan xabar matnini kiriting:',
        'product_list_empty': 'Hozir hech qanday mahsulot yo\'q',
        'about': 'SunLite — balans boshqaruvi va mahsulot sotib olish uchun ishonchli bot.'
    },
    'ru': {
        'welcome': 'Привет!',
        'choose_lang': 'Выберите язык:',
        'offer': 'Пожалуйста ознакомьтесь с офертой: <a href="https://example.com/oferta">Оферта</a>\nЕсли вы согласны — нажмите "Подтверждаю ✅".',
        'offer_confirmed': '💡 Теперь вы можете использовать SunLite бот!\nВыберите раздел в меню 👇',
        'enter_topup_amount': '💳 Пополнение счета\n\n💬 Введите сумму: (Минимум: {min} UZS, Максимум: {max} UZS)',
        'invalid_amount': 'Неверная сумма. Введите целое число в диапазоне {min}-{max}.',
        'send_screenshot': '📸 После оплаты пришлите скриншот!',
        'topup_sent_admin': 'Ваш платёж отправлен администратору.',
        'topup_approved': '🎉 Ваш счёт успешно пополнен на {amount} UZS!',
        'topup_rejected': 'Платёж отклонён. Свяжитесь с администратором.',
        'no_history': '📜 В истории пока ничего нет.',
        'ask_nickname': 'Введите ник для сервера (не возвращается):',
        'order_sent_admin': '🆕 Заказ отправлен администратору.',
        'order_confirmed_user': '✅ Ваш заказ успешно доставлен на аккаунт.',
        'insufficient_balance': 'Недостаточно средств. Пожалуйста пополните счёт.',
        'cancelled': 'Операция отменена 🔙',
        'admin_broadcast_prompt': 'Введите текст для рассылки:',
        'product_list_empty': 'Сейчас нет доступных товаров',
        'about': 'SunLite — надёжный бот для пополнения баланса и покупок.'
    }
}
